FROM node:16-alpine as builder

WORKDIR '/app'

COPY ./package.json ./
COPY ./pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

ARG VITE_APP_BASE_URL                    
ENV VITE_APP_BASE_URL=$VITE_APP_BASE_URL

COPY . .

RUN pnpm build

# nginx stage
FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html