version: "3.9"
services:
  client:
    image: "snr-react-local"
    hostname: client
    container_name: client-local
    env_file: .env.local
    build:
      dockerfile: Dockerfile.local
      context: ./client
      args:
        VITE_APP_BASE_URL: ${VITE_APP_BASE_URL}
  server:
    image: "snr-server-local"
    hostname: api
    container_name: server-local
    env_file: .env.local
    build:
      dockerfile: Dockerfile
      context: ./server
  nginx:
    image: "snr-nginx-local"
    hostname: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    container_name: nginx-local
