version: "3"

services:
  client:
    container_name: client-dev
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    container_name: server-dev
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file: .env.dev
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
  mongo:
    container_name: mongo-dev
    image: mongo:4.4-bionic
    env_file: .env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ADMIN_PWD
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_USERNAME=$DB_USER
      - MONGO_INITDB_PASSWORD=$DB_USER_PWD
    ports:
      - "${DB_PORT}:27017"
    networks:
      - mern-app
    volumes:
      - ./server/addons/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - dbdata:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  dbdata:
    driver: local
